version: "3"
services:
       node_server:
           container_name: node_server
           image: quizhub # Specify what image we are gonna use 
           restart: always
           build: .
           working_dir: /src
           ports:
               # <Port for outside world>:<Actual port of service in container>
             - "${PORT}:${NODE_DOCKER_PORT}"